# Generated by Django 5.1.15 on 2026-06-02 04:36

import django.db.models.deletion
import portal.apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensor',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identificador único do sensor (ex: mac, serial, node+index)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('hardware', models.CharField(blank=True, help_text='Informação de hardware / modelo', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(default=portal.apps.devices.models._generate_api_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='devices.sensortype')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
    ]
