# Generated by Django 5.1.15 on 2026-06-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorApiKeyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rotate', 'Rotate'), ('revoke', 'Revoke'), ('set', 'Set')], max_length=20)),
                ('old_key', models.CharField(blank=True, max_length=128, null=True)),
                ('new_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_audits', to='devices.sensor')),
            ],
            options={
                'verbose_name': 'Sensor API Key Audit',
                'verbose_name_plural': 'Sensor API Key Audits',
            },
        ),
    ]
